# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_openvector_entropy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entropy',
            old_name='name',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='openvector',
            old_name='name',
            new_name='word',
        ),
    ]
